### ISSUE TITLE
With a fresh install after entering 1st domain: spinner is shown, password field is empty

### ISSUE THREAD

**Issue by 607011** [ola-ct/Qt-SESAM#68]
Quick'n'dirty remedy: reselect domain in combobox.

**Comment by 607011** [comment]
Reselecting works only in some cases.

**Comment by 607011** [comment]
This seems to be a concurrency issue.

**Comment by 607011** [comment]
@Wikinaut reported that problem is still present.

Exploring …

**Comment by 607011** [comment]
Could not reproduce the reported bug by doing the following after a fresh install (i.e. no settings file present, not sync file or server set up):
- Type a domain name in combobox.
- Press TAB (-> opens New Domain Wizard).
- In New Domain Wizard press Accept.

Observations: All fields are correctly transferred to the main window. Password is generated. Spinner hidden after generation. 

Successfully tested on:
- Windows 7 (64 bit) with Qt 5.5.0, both 32 and 64 bit, running on physical machine with Intel Core i5 750 @ 2,67 GHz, 16 GByte RAM, 4 cores.
- openSUSE Tumbleweed 64 bit with Qt 5.4.2 running in VMware Player 12 with 2 GByte RAM, 2 CPUs.

Nonetheless, I could reproduce the bug by entering a new domain via Ctrl+N.

**Comment by Wikinaut** [comment]
Tjs, what shall I say?

**Comment by 607011** [comment]
I think I found the bug. Stay tuned.

**Comment by 607011** [comment]
Wahoooooo! That was a difficult birth ;-)

**Comment by 607011** [comment]
Bug fixed in branch [Issue-68](https://github.com/ola-ct/Qt-SESAM/tree/Issue-68).

Works on openSUSE Tumbleweed and Windows 7.

Can anyone confirm?@Wikinaut?

Please

```
git pull origin Issue-68
git checkout Issue-68
```

then build and test!

**Comment by 607011** [comment]
Resolved by commit a8d0cdf111a6de491de254430f95bc1dbd30195b.

**Comment by Wikinaut** [comment]
<s>The endless-loop is gone.</a> The problem with new domains still present. I added a first new domain, closed the program and restarted- Okay. Then New Domain. Tried to enter a new domain -- no way, it does not work. No password generated, or not saved, cannot track --- too many problems with this program.

CORRECTION:
https://github.com/ola-ct/Qt-SESAM/issues/56 is not solved.

**Comment by Wikinaut** [comment]
make warning:

```
In file included from ../../../../include/qt5/QtCore/qnamespace.h:37:0,
                 from ../../../../include/qt5/QtCore/qobjectdefs.h:41,
                 from ../../../../include/qt5/QtCore/qobject.h:40,
                 from ../../../../include/qt5/QtCore/QObject:1,
                 from ../libSESAM/util.h:25,
                 from optionsdialog.cpp:20:
optionsdialog.cpp: In member function ‘void OptionsDialog::onServerRootUrlChanged(QString)’:
../../../../include/qt5/QtCore/qglobal.h:979:43: warning: unused variable ‘d’ [-Wunused-variable]
 #define Q_D(Class) Class##Private * const d = d_func()
                                           ^
optionsdialog.cpp:244:3: note: in expansion of macro ‘Q_D’
   Q_D(OptionsDialog);

```

**Comment by Wikinaut** [comment]
I guess, you have to refactor your program. From scratch.

**Comment by 607011** [comment]
Tested latest commit on Xubuntu 15.04, Xubuntu 14.10, openSUSE Tumbleweed, Windows 7. Compiles fine. Runs fine. Neither #56 nor #68 appears.

**Comment by 607011** [comment]
Tested on another Ubuntu 15.04 (physical machine, not VM): no problems.

**Comment by 607011** [comment]
Tested on late 2011 MacBookPro running Mac OS X 10.10.5 and Qt 5.5.0: no problems.
